/* This file is generated by 'makedefs' for reference purposes only. */
/* It is no longer used in the NetHack build. */

#if !defined(CROSSCOMPILE) || !defined(CROSSCOMPILE_TARGET)
#define BUILD_DATE "Sun Jan 12 09:43:59 2025"
#define BUILD_TIME (1736693039UL)

#define VERSION_NUMBER 0x03070043UL
#define VERSION_FEATURES 0x00060040UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x211cf185UL
#define VERSION_SANITY2 0x290d42ac0UL
#define VERSION_SANITY3 0x0002a000UL

#define VERSION_STRING "3.7.0-67"
#define VERSION_ID \
 "MacOS NetHack Version 3.7.0-67 Work-in-progress - last build Sun Jan 12 09:43:59 2025."
#define COPYRIGHT_BANNER_C \
 "         Version 3.7.0-67 MacOS Work-in-progress, built Sun Jan 12 09:43:59 2025."
#endif /* !CROSSCOMPILE || !CROSSCOMPILE_TARGET */

